/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RemoteComputer;

import En_De_Coding.Encoder;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Danish
 */
public class RuntimeActionFrame extends javax.swing.JFrame {
DefaultListModel model=new DefaultListModel();
    /**
     * Creates new form RuntimeActionFrame
     */
    public RuntimeActionFrame() {
        initComponents();
        model.addElement("Notepad");
        model.addElement("Calculator");
        model.addElement("MS Paint");
        model.addElement("File Explorer");
        model.addElement("Open Request File");
        model.addElement("Character Map");
        model.addElement("Disk Clean Up");
        model.addElement("Commond Prompt");
        model.addElement("Connection Manager Profile Installer");
        model.addElement("Color Management");
        model.addElement("Computer Management");
        model.addElement("Controls");
        model.addElement("Stored User Names and Passwords");
        model.addElement("Cleartype Text Tuner");
        model.addElement("Phone Dialer");
        model.addElement("Protected Content Migration");
        model.addElement("Display");
        model.addElement("Window Media Player");
        model.addElement("Bluetooth File Transfer");
        model.addElement("Fax Cover Page Editer");
        model.addElement("Intel Graphic");
        model.addElement("IExpress Wizard");
        model.addElement("Task Manager");
        model.addElement("Instal or uninstal Display Languages");
        model.addElement("Magnify");
        model.addElement("Windows Mobility Center");
        model.addElement("Sync Center");
        model.addElement("Microsoft Support Diagnostic Tool");
        model.addElement("Windows Installer");
        model.addElement("System Information");
        model.addElement("Remote Desktop Connection");
        model.addElement("Printer Migration");
        model.addElement("Resources Moniter");
        model.addElement("Signature Verification");
        model.addElement("Activation");
        model.addElement("Volume Mixture"); 
        model.addElement("Snipping Tool");
        model.addElement("User Account Control Settings");         
       
        utilitiesList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        remoteIPLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        utilitiesList = new javax.swing.JList();
        actionButton = new javax.swing.JButton();
        remoteIPTextField = new javax.swing.JTextField();
        utilitiesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        remoteIPLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        remoteIPLabel.setText("REMOTE IP");
        getContentPane().add(remoteIPLabel);
        remoteIPLabel.setBounds(760, 40, 110, 20);

        utilitiesList.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jScrollPane1.setViewportView(utilitiesList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 80, 430, 540);

        actionButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        actionButton.setText("ACTION");
        actionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(actionButton);
        actionButton.setBounds(540, 540, 170, 80);

        remoteIPTextField.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        remoteIPTextField.setText("127.0.0.1");
        getContentPane().add(remoteIPTextField);
        remoteIPTextField.setBounds(760, 70, 160, 31);

        utilitiesLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        utilitiesLabel.setText("UTILITIES");
        getContentPane().add(utilitiesLabel);
        utilitiesLabel.setBounds(70, 50, 100, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButtonActionPerformed
        String selectedValue=(String) utilitiesList.getSelectedValue();
        selectedValue=Encoder.utilitiesEncode(selectedValue);
        Runtime run=Runtime.getRuntime();
    try {
        run.exec(selectedValue);
    } catch (IOException ex) {
        Logger.getLogger(RuntimeActionFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_actionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RuntimeActionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RuntimeActionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RuntimeActionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RuntimeActionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RuntimeActionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actionButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel remoteIPLabel;
    private javax.swing.JTextField remoteIPTextField;
    private javax.swing.JLabel utilitiesLabel;
    private javax.swing.JList utilitiesList;
    // End of variables declaration//GEN-END:variables
}
